# Generated by Django 4.1 on 2022-08-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genre', models.IntegerField(choices=[(1, 'Folklore'), (2, 'Drama'), (3, 'Poetry'), (4, 'Prose')], null=True)),
                ('author', models.CharField(max_length=50)),
                ('year_published', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshop.book')),
            ],
        ),
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.book')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house', models.IntegerField()),
                ('books', models.ManyToManyField(through='bookshop.InStock', to='bookshop.book')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50, null=True)),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('books', models.ManyToManyField(through='bookshop.BookSold', to='bookshop.book')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshop.shop')),
            ],
        ),
        migrations.AddField(
            model_name='instock',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.shop'),
        ),
        migrations.AddField(
            model_name='booksold',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookshop.purchase'),
        ),
    ]
